# Generated by Django 5.0.7 on 2024-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='../static/images/img.webp', upload_to=''),
        ),
    ]
