# Generated by Django 5.0.8 on 2024-08-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default='Test Run', max_length=255),
            preserve_default=False,
        ),
    ]
