# Generated by Django 5.0.8 on 2024-08-19 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subscriber_first_name_subscriber_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='send_at',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='scheduled_send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
