# Generated by Django 5.0.8 on 2024-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_remove_newsletter_send_at_remove_newsletter_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
