# Generated by Django 5.0.8 on 2024-08-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_subscriber_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='alias',
        ),
    ]
