# Generated by Django 5.0.8 on 2024-08-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_newsletter_scheduled_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
