# Generated by Django 5.0.7 on 2024-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default="Let's make Ethereum great again"),
            preserve_default=False,
        ),
    ]
