# Generated by Django 5.0.7 on 2024-08-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_remove_article_author_author_article_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
    ]
