# Generated by Django 5.0.7 on 2024-08-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
