# Generated by Django 5.0.7 on 2024-07-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_article_options_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=10),
        ),
    ]
