# Generated by Django 5.0.7 on 2024-08-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_article_category_article_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scheduled_publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
