# Generated by Django 5.0.7 on 2024-08-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_article_scheduled_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scheduled_publish_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
