# Generated by Django 5.0.8 on 2024-08-21 12:39

import apps.research.models.article
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default=apps.research.models.article.get_default_thumb, upload_to='images/'),
        ),
    ]
