# Generated by Django 5.0.8 on 2024-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_alter_article_summary_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
