# Generated by Django 5.0.7 on 2024-07-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_alter_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='images/img.webp', upload_to='images/'),
        ),
    ]
