# Generated by Django 5.0.8 on 2024-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_alter_article_summary_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
