# Generated by Django 5.0.8 on 2024-08-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_alter_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
    ]
