class ErrorCode:
    INVALID_PAGE = "invalid_page"
    INVALID_OWNER = 'invalid_owner'
    UNAUTHORIZED_USER = "unauthorized_user"
    NETWORK_FAILURE = "network_failure"
    SERVER_ERROR = "server_error"
    INVALID_ENTRY = "invalid_entry"
    OLD_EMAIL = "old_email"
    INCORRECT_OTP = "incorrect_otp"
    EXPIRED_OTP = "expired_otp"
    INVALID_CREDENTIALS = "invalid_credentials"
    UNVERIFIED_USER = "unverified_user"
    NON_EXISTENT = "non_existent"
    NOT_ALLOWED = "not_allowed"
    ALREADY_EXISTS = "already_exists"
    VERIFIED_USER = "verified_user"
    NO_ACCOUNT = "no_account"
    INVALID_DATA_TYPE = "invalid_data_type"
